version: '3.8'
services:
  api:
    container_name: pha-admin-be
    restart: always 
    build:
      context: ./
    env_file: .env
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    links:
      - mongodb
    volumes:
      - .:/admin-be
    networks:
      - admin-network
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb_data:/data/admin/db
    networks:
      - admin-network

volumes:
  mongodb_data:

networks:
  admin-network:
    driver: bridge
